package com.freelas.app.ui.client

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.freelas.app.data.model.Location
import com.freelas.app.data.model.Service
import com.freelas.app.data.model.ServiceCategory
import com.freelas.app.data.model.ServiceOffer
import com.freelas.app.data.model.Payment
import com.freelas.app.data.repository.ServiceRepository
import com.freelas.app.data.repository.LocationRepository
import com.freelas.app.data.repository.RealClientRepository
import com.freelas.app.data.repository.RealProviderRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ClientHomeViewModel @Inject constructor(
    private val serviceRepository: ServiceRepository,
    private val locationRepository: LocationRepository,
    private val realClientRepository: RealClientRepository,
    private val realProviderRepository: RealProviderRepository
) : ViewModel() {
    
    private val _uiState = MutableStateFlow(ClientHomeUiState())
    val uiState: StateFlow<ClientHomeUiState> = _uiState.asStateFlow()
    
    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()
    
    private val _errorMessage = MutableStateFlow<String?>(null)
    val errorMessage: StateFlow<String?> = _errorMessage.asStateFlow()
    
    init {
        getCurrentLocation()
        loadNearbyProviders()
        loadServiceCategories()
        loadServiceOffers()
    }
    
    fun updateOrigin(origin: String) {
        _uiState.value = _uiState.value.copy(origin = origin)
        calculateDistanceAndTime()
    }
    
    fun updateDestination(destination: String) {
        _uiState.value = _uiState.value.copy(destination = destination)
        calculateDistanceAndTime()
    }
    
    fun selectCategory(category: ServiceCategory) {
        _uiState.value = _uiState.value.copy(selectedCategory = category)
    }
    
    fun updateSelectedCategory(category: ServiceCategory?) {
        _uiState.value = _uiState.value.copy(selectedCategory = category)
    }
    
    fun updateCustomPrice(price: Double?) {
        _uiState.value = _uiState.value.copy(customPrice = price)
    }
    
    fun updateNegotiatedPrice(price: Double) {
        _uiState.value = _uiState.value.copy(negotiatedPrice = price)
    }
    
    fun toggleAutoAccept(enabled: Boolean) {
        _uiState.value = _uiState.value.copy(autoAcceptOffers = enabled)
    }
    
    private fun calculateDistanceAndTime() {
        val origin = _uiState.value.origin
        val destination = _uiState.value.destination
        
        if (origin.isNotEmpty() && destination.isNotEmpty()) {
            viewModelScope.launch {
                _isLoading.value = true
                
                realClientRepository.calculateRouteAndPricing(origin, destination)
                    .collect { result ->
                        result.fold(
                            onSuccess = { routeInfo ->
                                _uiState.value = _uiState.value.copy(
                                    distance = routeInfo.distance,
                                    estimatedTime = routeInfo.estimatedTime,
                                    routeInfo = routeInfo
                                )
                                _isLoading.value = false
                            },
                            onFailure = { exception ->
                                _errorMessage.value = "Erro ao calcular rota: ${exception.message}"
                                _isLoading.value = false
                            }
                        )
                    }
            }
        }
    }
    
    fun setAutoAcceptOffers(enabled: Boolean) {
        _uiState.value = _uiState.value.copy(autoAcceptOffers = enabled)
    }
    
    fun selectService(service: ServiceOption) {
        _uiState.value = _uiState.value.copy(selectedService = service)
    }
    
    fun createServiceRequest() {
        val state = _uiState.value
        if (validateServiceRequest(state)) {
            _isLoading.value = true
            
            viewModelScope.launch {
                try {
                    val service = Service(
                        id = "", // Will be generated by backend
                        clientId = "", // Will be set by backend
                        providerId = null,
                        category = state.selectedCategory ?: ServiceCategory.OTHER,
                        title = getServiceTitle(state.selectedCategory ?: ServiceCategory.OTHER),
                        description = "",
                        price = state.selectedService?.price ?: state.customPrice ?: 0.0,
                        status = com.freelas.app.data.model.ServiceStatus.PENDING,
                        location = state.currentLocation ?: Location(0.0, 0.0, ""),
                        destination = state.destinationLocation,
                        estimatedTime = state.selectedService?.estimatedTime ?: 30,
                        distance = state.distance ?: 0.0,
                        createdAt = java.util.Date(),
                        acceptedAt = null,
                        startedAt = null,
                        completedAt = null
                    )
                    
                    serviceRepository.createService(service)
                        .onSuccess { createdService ->
                            _isLoading.value = false
                            _uiState.value = _uiState.value.copy(
                                currentService = createdService,
                                isFindingProvider = true
                            )
                            startFindingProviders(createdService.id)
                        }
                        .onFailure { exception ->
                            _isLoading.value = false
                            _errorMessage.value = exception.message ?: "Erro ao criar solicitação"
                        }
                } catch (e: Exception) {
                    _isLoading.value = false
                    _errorMessage.value = e.message ?: "Erro inesperado"
                }
            }
        }
    }
    
    fun makeOffer(price: Double) {
        val state = _uiState.value
        val currentService = state.currentService ?: return
        
        _isLoading.value = true
        
        viewModelScope.launch {
            val offer = ServiceOffer(
                id = "", // Will be generated by backend
                serviceId = currentService.id,
                clientId = currentService.clientId,
                providerId = null,
                clientPrice = price,
                providerPrice = null,
                status = com.freelas.app.data.model.OfferStatus.PENDING,
                createdAt = java.util.Date(),
                expiresAt = java.util.Date(System.currentTimeMillis() + 300000), // 5 minutes
                autoAccept = state.autoAcceptOffers
            )
            
            serviceRepository.createOffer(offer)
                .onSuccess {
                    _isLoading.value = false
                    _uiState.value = _uiState.value.copy(
                        currentOffer = it,
                        isWaitingForOffers = true
                    )
                }
                .onFailure { exception ->
                    _isLoading.value = false
                    _errorMessage.value = exception.message ?: "Erro ao fazer oferta"
                }
        }
    }
    
    fun acceptOffer(offer: ServiceOffer) {
        _isLoading.value = true
        
        viewModelScope.launch {
            val updatedOffer = offer.copy(
                status = com.freelas.app.data.model.OfferStatus.ACCEPTED
            )
            
            serviceRepository.updateOffer(offer.id, updatedOffer)
                .onSuccess {
                    _isLoading.value = false
                    _uiState.value = _uiState.value.copy(
                        currentOffer = it,
                        isWaitingForOffers = false,
                        isServiceAccepted = true
                    )
                }
                .onFailure { exception ->
                    _isLoading.value = false
                    _errorMessage.value = exception.message ?: "Erro ao aceitar oferta"
                }
        }
    }
    
    fun rejectOffer(offer: ServiceOffer) {
        _isLoading.value = true
        
        viewModelScope.launch {
            val updatedOffer = offer.copy(
                status = com.freelas.app.data.model.OfferStatus.REJECTED
            )
            
            serviceRepository.updateOffer(offer.id, updatedOffer)
                .onSuccess {
                    _isLoading.value = false
                    _uiState.value = _uiState.value.copy(
                        currentOffer = null,
                        isWaitingForOffers = false
                    )
                }
                .onFailure { exception ->
                    _isLoading.value = false
                    _errorMessage.value = exception.message ?: "Erro ao recusar oferta"
                }
        }
    }
    
    fun cancelServiceRequest() {
        _uiState.value = _uiState.value.copy(
            currentService = null,
            currentOffer = null,
            isFindingProvider = false,
            isWaitingForOffers = false,
            isServiceAccepted = false
        )
    }
    
    private fun getCurrentLocation() {
        viewModelScope.launch {
            locationRepository.getCurrentLocation()
                .onSuccess { location ->
                    _uiState.value = _uiState.value.copy(
                        currentLocation = location,
                        origin = location.address
                    )
                }
                .onFailure { exception ->
                    _errorMessage.value = "Erro ao obter localização: ${exception.message}"
                }
        }
    }
    
    private fun loadNearbyProviders() {
        viewModelScope.launch {
            val state = _uiState.value
            val location = state.currentLocation
            
            if (location != null) {
                realProviderRepository.getNearbyProviders(
                    latitude = location.latitude,
                    longitude = location.longitude,
                    radius = 10.0
                ).collect { result ->
                    result.fold(
                        onSuccess = { providers ->
                            // Convert ServiceProviderProfile to User
                            val users = providers.map { profile ->
                                com.freelas.app.data.model.User(
                                    id = profile.userId,
                                    name = "Prestador ${profile.id.takeLast(4)}",
                                    email = "prestador${profile.id.takeLast(4)}@freelas.com",
                                    phone = "11999999999",
                                    userType = com.freelas.app.data.model.UserType.PROVIDER,
                                    isActive = profile.isAvailable,
                                    createdAt = java.util.Date(),
                                    profileImage = null,
                                    rating = profile.rating,
                                    totalServices = profile.totalServices
                                )
                            }
                            _uiState.value = _uiState.value.copy(
                                nearbyProviders = users
                            )
                        },
                        onFailure = { exception ->
                            _errorMessage.value = "Erro ao carregar prestadores: ${exception.message}"
                        }
                    )
                }
            }
        }
    }
    
    private fun startFindingProviders(serviceId: String) {
        // This would typically involve WebSocket communication
        // For now, we'll simulate the process
        viewModelScope.launch {
            // Simulate finding providers
            kotlinx.coroutines.delay(3000)
            
            // Simulate receiving offers
            val mockOffer = ServiceOffer(
                id = "offer_1",
                serviceId = serviceId,
                clientId = "client_1",
                providerId = "provider_1",
                clientPrice = _uiState.value.selectedService?.price ?: 15.0,
                providerPrice = 18.0,
                status = com.freelas.app.data.model.OfferStatus.PENDING,
                createdAt = java.util.Date(),
                expiresAt = java.util.Date(System.currentTimeMillis() + 300000)
            )
            
            _uiState.value = _uiState.value.copy(
                isFindingProvider = false,
                receivedOffers = listOf(mockOffer)
            )
        }
    }
    
    private fun validateServiceRequest(state: ClientHomeUiState): Boolean {
        return when {
            state.destination.isBlank() -> {
                _errorMessage.value = "Destino é obrigatório"
                false
            }
            state.selectedCategory == null -> {
                _errorMessage.value = "Selecione uma categoria de serviço"
                false
            }
            state.currentLocation == null -> {
                _errorMessage.value = "Localização não disponível"
                false
            }
            else -> true
        }
    }
    
    private fun getServiceTitle(category: ServiceCategory): String {
        return when (category) {
            ServiceCategory.DELIVERY -> "Entrega"
            ServiceCategory.TRANSPORT -> "Transporte"
            ServiceCategory.CLEANING -> "Limpeza"
            ServiceCategory.MAINTENANCE -> "Manutenção"
            ServiceCategory.CONSULTATION -> "Consultoria"
            ServiceCategory.OTHER -> "Serviço"
        }
    }
    
    fun clearError() {
        _errorMessage.value = null
    }
    
    fun selectServiceOffer(offer: ServiceOffer) {
        // Handle service offer selection
        _uiState.value = _uiState.value.copy(currentOffer = offer)
    }
    
    /**
     * Define o serviço atual
     */
    fun setCurrentService(service: Service) {
        _uiState.value = _uiState.value.copy(
            currentService = service
        )
    }
    
    /**
     * Inicia o processo de pagamento
     */
    fun startPayment() {
        val currentService = _uiState.value.currentService
        if (currentService != null) {
            _uiState.value = _uiState.value.copy(
                showPaymentScreen = true
            )
        }
    }
    
    /**
     * Processa pagamento bem-sucedido
     */
    fun onPaymentSuccess(transaction: Payment) {
        _uiState.value = _uiState.value.copy(
            showPaymentScreen = false,
            paymentTransaction = transaction,
            isServiceAccepted = true
        )
    }
    
    /**
     * Cancela o pagamento
     */
    fun cancelPayment() {
        _uiState.value = _uiState.value.copy(
            showPaymentScreen = false
        )
    }
    
    fun selectProvider(provider: com.freelas.app.data.model.User) {
        // Handle provider selection
    }
    
    fun handleRequestAction(requestId: String, action: String) {
        when (action) {
            "cancel" -> {
                // Cancel request
                _uiState.value = _uiState.value.copy(
                    activeRequests = _uiState.value.activeRequests.filter { it.id != requestId }
                )
            }
            "track" -> {
                // Navigate to tracking
            }
        }
    }
    
    private fun loadServiceCategories() {
        val mockCategories = listOf(
            ServiceCategory.TRANSPORT,
            ServiceCategory.DELIVERY,
            ServiceCategory.CLEANING,
            ServiceCategory.MAINTENANCE,
            ServiceCategory.CONSULTATION,
            ServiceCategory.OTHER
        )
        
        _uiState.value = _uiState.value.copy(categories = mockCategories)
    }
    
    private fun loadServiceOffers() {
        val mockOffers = listOf(
            ServiceOffer(
                id = "offer_1",
                serviceId = "service_1",
                clientId = "client_1",
                providerId = "provider_1",
                clientPrice = 15.0,
                providerPrice = 18.0,
                status = com.freelas.app.data.model.OfferStatus.PENDING,
                createdAt = java.util.Date(),
                expiresAt = java.util.Date(System.currentTimeMillis() + 300000)
            ),
            ServiceOffer(
                id = "offer_2",
                serviceId = "service_2", 
                clientId = "client_1",
                providerId = "provider_2",
                clientPrice = 18.0,
                providerPrice = 20.0,
                status = com.freelas.app.data.model.OfferStatus.PENDING,
                createdAt = java.util.Date(),
                expiresAt = java.util.Date(System.currentTimeMillis() + 300000)
            ),
            ServiceOffer(
                id = "offer_3",
                serviceId = "service_3",
                clientId = "client_1", 
                providerId = "provider_3",
                clientPrice = 25.0,
                providerPrice = 30.0,
                status = com.freelas.app.data.model.OfferStatus.PENDING,
                createdAt = java.util.Date(),
                expiresAt = java.util.Date(System.currentTimeMillis() + 300000)
            )
        )
        
        _uiState.value = _uiState.value.copy(serviceOffers = mockOffers)
    }
}

data class ClientHomeUiState(
    val currentLocation: Location? = null,
    val origin: String = "",
    val destination: String = "",
    val destinationLocation: Location? = null,
    val selectedCategory: ServiceCategory? = null,
    val selectedService: ServiceOption? = null,
    val customPrice: Double? = null,
    val negotiatedPrice: Double = 80.0,
    val autoAcceptOffers: Boolean = false,
    val currentService: Service? = null,
    val currentOffer: ServiceOffer? = null,
    val isFindingProvider: Boolean = false,
    val isWaitingForOffers: Boolean = false,
    val isServiceAccepted: Boolean = false,
    val nearbyProviders: List<com.freelas.app.data.model.User> = emptyList(),
    val receivedOffers: List<ServiceOffer> = emptyList(),
    val activeRequests: List<Service> = emptyList(),
    val serviceOffers: List<ServiceOffer> = emptyList(),
    val categories: List<ServiceCategory> = emptyList(),
    val distance: Double = 0.0,
    val estimatedTime: Int = 0,
    val routeInfo: com.freelas.app.data.repository.RouteInfo? = null,
    val showPaymentScreen: Boolean = false,
    val paymentTransaction: Payment? = null
)

data class ServiceOption(
    val id: String,
    val name: String,
    val price: Double,
    val estimatedTime: Int,
    val icon: String,
    val category: ServiceCategory,
    val hasDiscount: Boolean = false,
    val discountPercentage: Int = 0
)
