name: Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
      - name: Run tests
        run: |
          pytest -q
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} backend
        env:
          IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/freelas-backend:${{ github.sha }}
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.IMAGE_TAG }}
